FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3\
	python3-pip


RUN pip3 install jupyter
RUN pip3 install pandas
RUN pip3 install numpy==1.19
RUN pip3 install sklearn
RUN pip3 install setuptools
RUN pip3 install keras
RUN pip3 install tensorflow==2.4.1
RUN useradd -ms /bin/bash jupyter


USER jupyter

WORKDIR /home/jupyter
COPY . .

RUN pip3 install mypackage

EXPOSE 8888
ENTRYPOINT ["jupyter","notebook","--ip=*"]

