FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3\
	python3-pip


RUN pip3 install jupyter
RUN pip3 install pandas
RUN pip3 install sklearn
RUN pip3 install nltk
RUN pip3 install Pillow==2.6.1
RUN pip3 install wordcloud
RUN pip3 install matplotlib
RUN pip3 install emoji
RUN pip3 install plotly

RUN useradd -ms /bin/bash jupyter

USER jupyter

WORKDIR /home/jupyter
COPY . .

EXPOSE 8888
ENTRYPOINT ["jupyter","notebook","--ip=*"]